name: Build and Publish to GitLab Pages

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the version of Node.js you need

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Grant execute permission for Gradlew
      run: chmod +x gradlew

    - name: Build wasmJs
      run: ./gradlew wasmJsBrowserDistribution

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wasmJs-artifacts
        path: composeApp/build/dist/wasmJs/productionExecutable

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: wasmJs-artifacts
        path: composeApp/build/dist/wasmJs/productionExecutable  # Specify the path where you want the artifact to be downloaded

    - name: Deploy to GitLab Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: pages  # Specify the target branch for GitLab Pages
        build_dir: ./artifact  # This should match the path you downloaded the artifact to
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Replace with the correct token for authentication